apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-task
spec:
  params:
    - name: log-line-bytes
      description: Number of bytes in the log line
      default: "1000"
      type: string
    - name: num-log-lines
      description: Number of lines to print to the log
      default: "10"
      type: string
  steps:
    - name: echo
      image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi@sha256:4aaabf49950796d9004f6e4f04ff53ab24dcd3fd29d8cc719a9b81f7546d31f2
      env:
        - name: LOG_LINE_BYTES
          value: $(params.log-line-bytes)
        - name: LOG_LINES
          value: $(params.num-log-lines)
      script: |
        #!/usr/bin/env bash

        # Create a file with LOG_LINE_BYTES random characters in a single line
        < /dev/urandom tr -dc "[:alnum:]" | head -c${LOG_LINE_BYTES} > file.txt

        # cat the file to stdout LOG_LINES times
        count=0
        for i in $(seq 0 ${LOG_LINES})
        do
          echo $count
          cat file.txt
          echo -e ' And another line for you...'
          count=count+1
          sleep 1s
        done
